services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: zilpzalp-backend
    ports:
      - "8000:8000"
    environment:
      ZILPZALP_CONFIG: /config/config.yaml
    volumes:
      - ./demo/config:/config
      - ./demo/data/inbox:/data/inbox
      - ./demo/data/error:/data/error
      - ./demo/data/processed:/data/processed
      - ./demo/targets:/targets
    restart: unless-stopped

  docs:
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    image: zilpzalp-docs
    ports:
      - "8001:80"
    restart: unless-stopped
