# syntax=docker/dockerfile:1

FROM squidfunk/mkdocs-material:9 AS dev

WORKDIR /docs
COPY mkdocs/ ./

FROM dev AS build
RUN mkdocs build --strict

FROM nginx:alpine AS serve
COPY --from=build /docs/site /usr/share/nginx/html
EXPOSE 80
