services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: zilpzalp-backend
    ports:
      - "8080:8000"
    volumes:
      - ./docker/backend/config:/config
      - ./docker/backend/data/inbox:/data/inbox
      - ./docker/backend/data/error:/data/error
      - ./docker/backend/data/trash:/data/trash
      - ./docker/backend/data/cache:/data/cache
      - ./docker/backend/data/outbox:/data/outbox
    restart: unless-stopped

  docs:
    build:
      target: dev
      context: .
      dockerfile: Dockerfile.mkdocs
    image: zilpzalp-docs
    volumes:
      - ./mkdocs:/docs
    ports:
      - "8081:8000"
    restart: unless-stopped
    command: serve --dev-addr=0.0.0.0:8000 --livereload
